### ISSUE TITLE
AttributeError: module 'constants' has no attribute 'visituserinfo'

### ISSUE THREAD

**Issue by ghost** [mvabdi/vsco-scraper#1]
I'm getting the following error when trying trying to scrape a profile.

Command used: `vsco-scraper username`

```bash
Traceback (most recent call last):
  File "/usr/local/bin/vsco-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/vscoscrape/vscoscrape.py", line 147, in main
    scraper = Scraper(args.username)
  File "/usr/local/lib/python3.5/dist-packages/vscoscrape/vscoscrape.py", line 19, in __init__
    self.session.get("http://vsco.co/content/Static/userinfo?callback=jsonp_%s_0"% (str(round(time.time()*1000))),headers=constants.visituserinfo)
AttributeError: module 'constants' has no attribute 'visituserinfo'
```

**Comment by mvabdi** [comment]
I updated the tarball at pypi, maybe that was the issue? I uninstalled my local version and used the pip version and the command worked.

Try updating it

**Comment by ghost** [comment]
I've uninstalled and reinstalled and still get the same issue

command: `vsco-scraper username --getImages`
```bash
Traceback (most recent call last):
  File "/usr/local/bin/vsco-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/vscoscrape/vscoscrape.py", line 185, in main
    scraper = Scraper(args.username)
  File "/usr/local/lib/python3.5/dist-packages/vscoscrape/vscoscrape.py", line 19, in __init__
    self.session.get("http://vsco.co/content/Static/userinfo?callback=jsonp_%s_0"% (str(round(time.time()*1000))),headers=constants.visituserinfo)
AttributeError: module 'constants' has no attribute 'visituserinfo'
```

Also, now that I run `vsco-scraper username` without the --getImages flag, nothing happens.

Thanks

**Comment by mvabdi** [comment]
It should work now
