### ISSUE TITLE
Traceback (most recent call last) error

### ISSUE THREAD

**Issue by ntoni** [mvabdi/vsco-scraper#19]
Hello there
I get this error when I try to --getImages

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/vsco-scraper", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vscoscrape/vscoscrape.py", line 372, in main
    scraper = Scraper(args.username)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vscoscrape/vscoscrape.py", line 28, in __init__
    self.newSiteId()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vscoscrape/vscoscrape.py", line 39, in newSiteId
    self.siteid = res.json()["sites"][0]["id"]
KeyError: 'sites'
```
What could it be?
Thanks

**Comment by mvabdi** [comment]
Is it only with the --getImages command? I would guess that vsco updated their json to use some other key

If it's just the getImages, then there is probably a bug. If I have time I will look at it in the next few days.

**Comment by mvabdi** [comment]
I am going to close this, since it has been up for a while.

My current guess is just that you are putting in the wrong username.
