### ISSUE TITLE
vsco-scraper in linux do not download use profile

### ISSUE THREAD

**Issue by estatistics** [mvabdi/vsco-scraper#44]
the user exists but dont download its images

```
vsco-scraper  --all iridaal
Traceback (most recent call last):
  File "/home/elias/.local/bin/vsco-scraper", line 8, in <module>
    sys.exit(main())
  File "/home/elias/.local/lib/python3.10/site-packages/vscoscrape/vscoscrape.py", line 842, in main
    with open(args.username, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'iridaal'

```

**Comment by Pewlaries** [comment]
The --all command is used with an input file, and is used to grab everything from all usernames in said file. I think you have to run --getImages etc. instead to get everything from a single profile if you don't use a file.
