### ISSUE TITLE
KeyError when trying to download

### ISSUE THREAD

**Issue by SilverMight** [mvabdi/vsco-scraper#5]
Getting this error when attempting to use --getImages on an account:

> Traceback (most recent call last):
  File "/usr/bin/vsco-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/vscoscrape/vscoscrape.py", line 211, in main
    scraper = Scraper(args.username)
  File "/usr/lib/python3.6/site-packages/vscoscrape/vscoscrape.py", line 26, in __init__
    self.newSiteId()
  File "/usr/lib/python3.6/site-packages/vscoscrape/vscoscrape.py", line 33, in newSiteId
    self.siteid = res.json()["sites"][0]["id"]
KeyError: 'sites'

**Comment by SilverMight** [comment]
My bad, believe I had an existing folder with the same name that caused the issue
