### ISSUE TITLE
Error om python3.12 termux

### ISSUE THREAD

**Issue by JaKrIvMa** [mvabdi/vsco-scraper#52]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/vsco-scraper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/vscoscrape/vscoscrape.py", line 842, in main
    with open(args.username, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'username of the user to scrape'

**Comment by Tyen3** [comment]
What does the command line look like that you're using to run vsco-scraper?

**Comment by JaKrIvMa** [comment]
Ran a wrong command sorry
